### ISSUE TITLE
Connection closed for unknown reason

### ISSUE THREAD

**Issue by BennyM** [hdinsight/hdinsight-storm-examples#13]
Lately I've been having a lot of issues running topologies. Two errors occur quite often, giving no indication as to what's wrong.

```
2015-08-12 08:58:08 b.s.d.executor [ERROR] 
java.lang.RuntimeException: com.microsoft.eventhubs.client.EventHubException: org.apache.qpid.amqp_1_0.client.ConnectionClosedException: Connection closed for unknown reason
	at com.microsoft.eventhubs.spout.EventHubSpout.open(EventHubSpout.java:156) ~[stormjar.jar:na]
	at backtype.storm.daemon.executor$fn__5064$fn__5079.invoke(executor.clj:542) ~[storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at backtype.storm.util$async_loop$fn__550.invoke(util.clj:463) ~[storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]
Caused by: com.microsoft.eventhubs.client.EventHubException: org.apache.qpid.amqp_1_0.client.ConnectionClosedException: Connection closed for unknown reason
	at com.microsoft.eventhubs.client.EventHubConsumerGroup.ensureSessionCreated(EventHubConsumerGroup.java:64) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.client.EventHubConsumerGroup.createReceiver(EventHubConsumerGroup.java:39) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.client.ResilientEventHubReceiver.initialize(ResilientEventHubReceiver.java:63) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.spout.EventHubReceiverImpl.open(EventHubReceiverImpl.java:74) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.spout.SimplePartitionManager.open(SimplePartitionManager.java:77) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.spout.EventHubSpout.preparePartitions(EventHubSpout.java:134) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.spout.EventHubSpout.open(EventHubSpout.java:153) ~[stormjar.jar:na]
	... 4 common frames omitted
Caused by: org.apache.qpid.amqp_1_0.client.ConnectionClosedException: Connection closed for unknown reason
	at org.apache.qpid.amqp_1_0.client.Connection.checkNotClosed(Connection.java:338) ~[stormjar.jar:na]
	at org.apache.qpid.amqp_1_0.client.Connection.createSession(Connection.java:322) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.client.EventHubConsumerGroup.ensureSessionCreated(EventHubConsumerGroup.java:61) ~[stormjar.jar:na]
	... 10 common frames omitted
```

```
2015-08-12 08:59:44 b.s.d.executor [ERROR] 
java.lang.NullPointerException: null
	at org.apache.qpid.amqp_1_0.transport.ConnectionEndpoint.getFirstFreeChannel(ConnectionEndpoint.java:327) ~[stormjar.jar:na]
	at org.apache.qpid.amqp_1_0.transport.ConnectionEndpoint.createSession(ConnectionEndpoint.java:230) ~[stormjar.jar:na]
	at org.apache.qpid.amqp_1_0.client.Session.<init>(Session.java:58) ~[stormjar.jar:na]
	at org.apache.qpid.amqp_1_0.client.Connection.createSession(Connection.java:323) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.client.EventHubConsumerGroup.ensureSessionCreated(EventHubConsumerGroup.java:61) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.client.EventHubConsumerGroup.createReceiver(EventHubConsumerGroup.java:39) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.client.ResilientEventHubReceiver.initialize(ResilientEventHubReceiver.java:63) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.spout.EventHubReceiverImpl.open(EventHubReceiverImpl.java:74) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.spout.SimplePartitionManager.open(SimplePartitionManager.java:77) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.spout.EventHubSpout.preparePartitions(EventHubSpout.java:134) ~[stormjar.jar:na]
	at com.microsoft.eventhubs.spout.EventHubSpout.open(EventHubSpout.java:153) ~[stormjar.jar:na]
	at backtype.storm.daemon.executor$fn__5064$fn__5079.invoke(executor.clj:542) [storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at backtype.storm.util$async_loop$fn__550.invoke(util.clj:463) [storm-core-0.9.3.2.2.7.1-0004.jar:0.9.3.2.2.7.1-0004]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]
```

**Comment by rtandonmsft** [comment]
@BennyM Thanks for reporting and using our service.
One of the reasons I know where can happen is if your connection is being throttled. 
These errors are usually retried i.e. the spout task will re-establish the connection if its dropped. Did you see that happen?

The error message should certainly be improved to make that clear (if that's the case). I know that it is much more clearer in the C# client for EventHubs.

# Understanding the EventHubs throughput units
EventHubs by default has a concept of throughput units that you find under the "scale" tab in your namespace. Each unit means 1 MB/s.

This bandwidth is shared across your entire namespace not a single EventHubs. So if you have multiple services underneath this namespace, they will share the throughput.

You can go increase upto 20 throughput units in the Azure Portal, which gives you 20 MB/s across your name space. So with 8 partitions single EvenHubs in a namespace, each partition can get 2.5 MB/s.

Also a single partition cannot go beyond 5 MB/s. So its best to create the partitions based on categorization of your data. The scaling however should be handled via the throughput units.

On contacting support the number of partitions and the throughput can be increased to larger numbers like 128 partitions and 100 units as well.

Through enterprise contracts, EventHubs also provides throughput upto 1 GB/s.

Hope this helps, let me know if you have follow-up questions in this regard. I will also bring this in notice to the EventHubs team.

# How to troubleshoot if it was indeed throttling
One of the ways I can think of is contacting Azure Customer Support, providing them with the EventHub details, the partitions where this happened and the time ranges. Someone from support or the product team should be able to guide on why such errors happened in your EventHubs at that time.

**Comment by rtandonmsft** [comment]
If there are issues with connections, we recommend to use newer storm-eventhubs from the hdinsight repository for now. These changes will make it to Apache Storm as well.

A new client for azure-event-hubs is also available now, which should hopefully address connectivity issues better. Right now, I have opened this issue in storm-eventhubs to track that ask: https://github.com/hdinsight/storm-eventhubs/issues/11
